Repository Catrobat/Catty, pull requests merged in 2020-08, with the labels that each got.

#1459 CATTY-359 Add rounded borders for preview images
  src/Catty/Defines/UIDefines.h
  src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
  src/Catty/ViewController/Download/ChartProjects/ChartProjectCell.swift
  src/Catty/ViewController/Download/SearchStore/SearchStoreCell.swift
  src/Catty/ViewController/Projects/MyProjectsViewController.m
Labels: code review passed

#1453 CATTY-401 Uploading a project with multiple tags/categories displays categories with wrong separator
  src/Catty/ViewController/Upload/UploadViewController.swift
  src/CattyTests/ViewController/UploadViewControllerTests.swift
Labels: code review passed

#1443 CATTY-273 Moving defines into the right directories and fixing all th…
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/Look/Look.m
  src/Catty/DataModel/Project/Project.h
  src/Catty/DataModel/SpriteObject/SpriteObject.h
  src/Catty/DataStructures/ProjectLoadingInfo/ProjectLoadingInfo.m
  src/Catty/Defines/NetworkDefines.swift
  src/Catty/Defines/ProjectDefines.h
  src/Catty/Defines/ViewControllerDefines.h
  src/Catty/Store/StoreProjectUploader.swift
  src/Catty/Supporting Files/Catty-Bridging-Header.h
  src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
  src/Catty/ViewController/CatrobatTableViewController/SettingsTableViewController.swift
  src/Catty/ViewController/Download/ProjectDetailStoreViewController.m
  src/Catty/ViewController/Projects/MyProjectsViewController.m
  src/Catty/ViewController/Upload/LoginViewController.m
  src/Catty/ViewController/Upload/RegisterViewController.m
  src/Catty/ViewController/Upload/UploadViewController.swift
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/BrickCell.h
  src/CattyTests/Store/Upload/StoreProjectUploaderTests.swift
  src/CattyTests/Utils/LoginViewControllerTests.swift
Labels: code review passed

#1451 CATTY-393 Fetch project tags from API
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Defines/NetworkDefines.swift
  src/Catty/Store/StoreProjectUploader.swift
  src/Catty/ViewController/Upload/UploadViewController.swift
  src/CattyTests/Mocks/StoreProjectUploaderMock.swift
  src/CattyTests/Store/Upload/Fixture/StoreProjectUpload.fetchTags.invalidLanguageTag.json
  src/CattyTests/Store/Upload/Fixture/StoreProjectUpload.fetchTags.success.json
  src/CattyTests/Store/Upload/StoreProjectUploaderTests.swift
Labels: code review passed

#1461 CATTY-405 Project with multiple tags/categories only shows one tag at selection
  src/Catty/PlayerEngine/Instructions/Look/SayForBubbleBrick+Instruction.swift
  src/Catty/PlayerEngine/Instructions/Look/ThinkForBubbleBrick+Instruction.swift
  src/Catty/PlayerEngine/Instructions/Motion/GlideToBrick+Instruction.swift
  src/Catty/ViewController/Upload/UploadCategoryViewController.swift
Labels: code review passed

#1464 Catty-406: testCopyObjectWithIfBricks.swift fail sometimes
  src/CattyUITests/ObjectTVCTests.swift
Labels: code review pending

#1460 CATTY-394 Use API to fetch project tags in UploadViewController
  src/Catty/Defines/NetworkDefines.swift
  src/Catty/Storyboard+XIB/iPhone.storyboard
  src/Catty/ViewController/Upload/UploadCategoryViewController.swift
  src/Catty/ViewController/Upload/UploadViewController.swift
  src/CattyTests/Mocks/StoreProjectUploaderMock.swift
  src/CattyTests/ViewController/UploadCategoryViewControllerTests.swift
  src/CattyTests/ViewController/UploadViewControllerTests.swift
Labels: in code review

#1457 CATTY-385 Add default screenshot to newly created projects
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/Project/Project.h
  src/Catty/DataModel/Project/Project.m
  src/Catty/Defines/UIDefines.swift
  src/Catty/Extension&Delegate&Protocol/Extensions/CBFileManagerExtension.swift
  src/Catty/IO/FileManager/CBFileManager.h
  src/Catty/IO/FileManager/CBFileManager.m
  src/Catty/IO/ProjectManager.swift
  src/Catty/Images.xcassets/DefaultScreenshots/Contents.json
  src/Catty/Images.xcassets/DefaultScreenshots/catrobat.imageset/Contents.json
  src/Catty/Images.xcassets/DefaultScreenshots/catrobat.imageset/catrobat.png
  src/Catty/Images.xcassets/DefaultScreenshots/elephant.imageset/Contents.json
  src/Catty/Images.xcassets/DefaultScreenshots/elephant.imageset/elephant.png
  src/Catty/Images.xcassets/DefaultScreenshots/lynx.imageset/Contents.json
  src/Catty/Images.xcassets/DefaultScreenshots/lynx.imageset/lynx.png
  src/Catty/Images.xcassets/DefaultScreenshots/panda.imageset/Contents.json
  src/Catty/Images.xcassets/DefaultScreenshots/panda.imageset/panda.png
  src/Catty/Images.xcassets/DefaultScreenshots/pingu.imageset/Contents.json
  src/Catty/Images.xcassets/DefaultScreenshots/pingu.imageset/pingu.png
  src/Catty/Images.xcassets/DefaultScreenshots/racoon.imageset/Contents.json
  src/Catty/Images.xcassets/DefaultScreenshots/racoon.imageset/racoon.png
  src/Catty/Images.xcassets/Webview/Contents.json
  src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
  src/Catty/ViewController/Projects/MyProjectsViewController.m
  src/CattyTests/Bricks/ChangeBrightnessByNBrickTests.swift
  src/CattyTests/Bricks/ChangeColorByNBrickTests.swift
  src/CattyTests/Bricks/ClearGraphicEffectBrickTests.swift
  src/CattyTests/Bricks/NextLookBrickTests.swift
  src/CattyTests/Bricks/PreviousLookBrickTests.swift
  src/CattyTests/Bricks/SetBackgroundBrickTests.swift
  src/CattyTests/Bricks/SetBrightnessBrickTests.swift
  src/CattyTests/Bricks/SetColorBrickTests.swift
  src/CattyTests/Bricks/SetLookBrickTests.swift
  src/CattyTests/FileManager/CBFileManagerTests.swift
  src/CattyTests/FileManager/ProjectManagerTests.swift
  src/CattyTests/Mocks/CBFileManagerMock.swift
  src/CattyTests/Mocks/RuntimeImageCacheMock.swift
  src/CattyTests/Parser & Serialization/Helper/CBXMLParserHelperTests.swift
  src/CattyTests/PlayerEngine/CBBackendTests.swift
  src/CattyTests/ViewController/Scene/StagePresenterViewControllerTest.swift
Labels: code review pending

#1456 CATTY-402 Modify Grid View for Landscape Mode
  src/Catty/ViewController/Stage/StagePresenterViewController.h
  src/Catty/ViewController/Stage/StagePresenterViewController.m
  src/CattyTests/ViewController/Scene/StagePresenterViewControllerTest.swift
Labels: code review passed

#1455 CATTY-335 Scene Presenter Landscape Mode
  src/Catty/ViewController/BaseViewController/BaseCollectionViewController.m
  src/Catty/ViewController/BaseViewController/BaseTableViewController.m
  src/Catty/ViewController/Stage/StagePresenterViewController.m
Labels: code review passed
