Repository Catrobat/Catty, pull requests merged in 2020-10, with the labels that each got.

#1489 CATTY-256 Convert NSMutableArray to Swift
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Extension&Delegate&Protocol/Extensions/NSMutableArrayExtension.swift
  src/Catty/ViewController/Continue&New/SceneTableViewController.m
  src/Catty/ViewController/Projects/MyProjectsViewController.m
  src/CattyTests/Extensions/NSMutableArrayExtensionTests.swift
Labels: code review passed

#1492 CATTY-414 Fix Copy "Go to [object]" Brick
  src/Catty/DataModel/Bricks/Motion/GoToBrick.m
Labels: code review passed

#1496 CATTY-192 Support for Xcode 11.7
  src/Catty/BluetoothHelper/BluetoothHelper/Helper/String+Extensions.swift
  src/Catty/BluetoothHelper/BluetoothHelper/Serialize:Deserialize/Data+Extensions.swift
  src/Catty/BluetoothHelper/BluetoothHelper/Serialize:Deserialize/SerializerDeserializer.swift
  src/Catty/FormulaEditor/InternFormulaParser.h
  src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
  src/Catty/Helpers/Firmata/Firmata.swift
  src/CattyTests/BluetoothDevices/Firmata/FirmataTests.swift
  src/CattyTests/Extensions/UIImageExtensionTests.swift
  src/CattyTests/Formula/FormulaElementTest.swift
  src/CattyTests/Formula/FormulaParserErrorDetectionTest.m
  src/CattyTests/Formula/FormulaParserFunctionsTest.m
  src/CattyTests/Formula/FormulaParserOperatorsTest.m
  src/CattyTests/Formula/FormulaParserTest.m
  src/CattyTests/Formula/FormulaTest.swift
Labels: code review pending

#1491 CATTY-419 Refactor disable Scripts
  src/Catty/Extension&Delegate&Protocol/Extensions/Notification/NotificationExtension.swift
  src/Catty/Firebase/FirebaseAnalyticsReporter.swift
  src/Catty/Firebase/FirebaseCrashlyticsReporter.swift
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController+Disable.swift
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
  src/CattyTests/Firebase/FirebaseAnalyticsTests.swift
  src/CattyTests/Firebase/FirebaseCrashlyticsReporterTests.swift
  src/CattyTests/ViewController/ScriptCollectionViewControllerDisableTests.swift
Labels: code review pending

#1495 CATTY-423 Display error for object preview images after changing to portrait/landscape mode
  src/Catty/ViewController/BaseViewController/BaseTableViewController.m
Labels: in code review

#1480 CATTY-378 Implemented AskBrick
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/Bricks/Look/AskBrick.swift
  src/Catty/DataModel/UserData/UserVariable.swift
  src/Catty/Defines/LanguageTranslationDefines.h
  src/Catty/Defines/LanguageTranslationDefinesSwift.swift
  src/Catty/Defines/SpriteKitDefines.swift
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/LookBricks/AskBrick+CBXMLHandler.swift
  src/Catty/PlayerEngine/Instructions/Data/ChangeVariableBrick+Instruction.swift
  src/Catty/PlayerEngine/Instructions/Data/SetVariableBrick+Instruction.swift
  src/Catty/PlayerEngine/Instructions/Data/ShowTextBrick+Instruction.swift
  src/Catty/PlayerEngine/Instructions/Look/AskBrick+Instruction.swift
  src/Catty/PlayerEngine/Stage/Stage.swift
  src/Catty/Resources/Localization/en.lproj/Localizable.strings
  src/Catty/Setup/CatrobatSetup+Bricks.swift
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/AskBrickCell.swift
  src/CattyTests/Bricks/AskBrickTests.swift
  src/CattyTests/CatrobatLanguage0.992/XMLParserTests/Unit Tests/XMLParserTests0992.swift
  src/CattyTests/DataModel/UserVariableTests.swift
  src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0992.xml
  src/CattyTests/Scene/StageTests.swift
  src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift
Labels: code review passed

#1499 CATTY-194 fix unexpected brush tool behaviour
  src/Catty/PocketPaint/Tools/MirrorRotationZoomTool.m
Labels: code review pending

#1493 CATTY-398 change icons
  src/Catty/Images.xcassets/Icons/ic_looks.imageset/Icons_looks.png
  src/Catty/Images.xcassets/Icons/ic_scripts.imageset/Icons_scripts.png
  src/Catty/Images.xcassets/Icons/ic_sounds.imageset/Icons_sounds.png
  src/Catty/Storyboard+XIB/iPhone.storyboard
Labels: code review passed

#1488 CATTY-157 fixed parameter input problem with long numbers
  src/Catty/FormulaEditor/InternToExternGenerator.m
  src/CattyTests/Formula/InternFormulaTest.m
Labels: code review passed

#1500 CATTY-424 upgrade crashlytics sdk
  src/Cartfile
  src/Cartfile.resolved
  src/Catty.xcodeproj/project.pbxproj
Labels: code review pending

#1515 CATTY-431 Remove TODO comment in Script+CBXMLHandler
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Scripts/Script+CBXMLHandler.m
Labels: code review passed

#1513 CATTY-433 Remove TODO comments in CBXMLParserHelper
  src/Catty/Parser&Serialializer/New Parser & Serializer/Helper/CBXMLParserHelper.m
Labels: code review passed

#1511 CATTY-287 Add tests for BrickFormulaProtocol 4/4
  src/Catty.xcodeproj/project.pbxproj
  src/CattyTests/Bricks/AddItemToUserListBrickTests.swift
  src/CattyTests/Bricks/ChangeVariableBrickTests.swift
  src/CattyTests/Bricks/ChangeVolumeByNBrickTests.swift
  src/CattyTests/Bricks/DeleteItemOfUserListBrickTests.swift
  src/CattyTests/Bricks/InsertItemIntoUserListBrickTests.swift
  src/CattyTests/Bricks/ReplaceItemInUserListBrickTests.swift
  src/CattyTests/Bricks/SetVariableBrickTests.swift
  src/CattyTests/Bricks/SetVolumeToBrickTests.swift
  src/CattyTests/Bricks/SetXBrickTests.swift
  src/CattyTests/Bricks/SetYBrickTests.swift
  src/CattyTests/Bricks/ShowTextBrickTests.swift
  src/CattyTests/Bricks/SpeakAndWaitBrickTests.swift
  src/CattyTests/Bricks/SpeakBrickTests.swift
  src/CattyTests/Bricks/TurnLeftBrickTests.swift
  src/CattyTests/Bricks/TurnRightBrickTests.swift
  src/CattyTests/Bricks/VibrationBrickTests.swift
Labels: in code review

#1508 CATTY-285 Add tests for BrickFormulaProtocol 2/4
  src/Catty.xcodeproj/project.pbxproj
  src/CattyTests/Bricks/ChangeTransparencyByNBrickTests.swift
  src/CattyTests/Bricks/PhiroMotorMoveBackwardBrickTests.swift
  src/CattyTests/Bricks/PhiroMotorMoveForwardBrickTests.swift
  src/CattyTests/Bricks/PhiroPlayToneBrickTests.swift
  src/CattyTests/Bricks/PhiroRGBLightBrickTests.swift
  src/CattyTests/Bricks/SayBubbleBrickTests.swift
  src/CattyTests/Bricks/SayForBubbleBrickTests.swift
  src/CattyTests/Bricks/SetBrightnessBrickTests.swift
  src/CattyTests/Bricks/SetColorBrickTests.swift
  src/CattyTests/Bricks/SetTransparencyBrickTests.swift
Labels: in code review

#1498 CATTY-360 Use SynchronizedArray in CBScheduler
  src/Catty/DataModel/Array/SynchronizedArray.swift
  src/Catty/PlayerEngine/Scheduler/CBScheduler.swift
  src/CattyTests/Bricks/WaitBrickTests.swift
  src/CattyTests/DataModel/SynchronizedArrayTests.swift
Labels: in code review

#1518 CATTY-432 Add tests for Look
  src/CattyTests/DataModel/LookTest.swift
Labels: code review pending

#1510 CATTY-436 Do not cache images on file system
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/Look/Look.h
  src/Catty/DataModel/Look/Look.m
  src/Catty/DataModel/SpriteObject/SpriteObject.h
  src/Catty/DataModel/SpriteObject/SpriteObject.m
  src/Catty/Defines/ProjectDefines.h
  src/Catty/Defines/UIDefines.swift
  src/Catty/Extension&Delegate&Protocol/Extensions/CBFileManagerExtension.swift
  src/Catty/Helpers/ImageCache/RuntimeImageCache.h
  src/Catty/Helpers/ImageCache/RuntimeImageCache.m
  src/Catty/IO/ProjectManager.swift
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LookImageViewController.m
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m
  src/Catty/ViewController/Continue&New/SceneTableViewController.m
  src/Catty/ViewController/Stage/StagePresenterViewControllerScreenshotExtension.swift
  src/CattyTests/CattyTests-Bridging-Header.h
  src/CattyTests/Extensions/UIImageExtensionTests.swift
  src/CattyTests/FileManager/CBFileManagerTests.swift
  src/CattyTests/FileManager/ProjectManagerTests.swift
  src/CattyTests/ImageCache/RuntimeImageCacheTests.swift
  src/CattyTests/Mocks/CBFileManagerMock.swift
  src/CattyTests/Mocks/RuntimeImageCacheMock.swift
  src/CattyTests/Resources/Images/transparency_gray_alpha.png
  src/CattyTests/Resources/Images/transparency_rgb.png
  src/CattyTests/Resources/Images/transparency_rgba.png
  src/CattyTests/ViewController/LookImageViewControllerTests.swift
  src/CattyTests/ViewController/LooksTableViewControllerTests.swift
  src/CattyTests/ViewController/Stage/StagePresenterViewControllerScreenshotTests.swift
  src/CattyTests/ViewController/Stage/StagePresenterViewControllerTests.swift
Labels: code review pending

#1522 CATTY-455 Add tests for sounds
  src/CattyTests/DataModel/SoundTest.swift
Labels: code review passed
