Repository Catrobat/Catty, pull requests merged in 2020-06, with the labels that each got.

#1373 CATTY-258 Convert NSString extension to Swift
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/Bricks/Brick.m
  src/Catty/DataModel/Bricks/Look/SayBubbleBrick.m
  src/Catty/DataModel/Bricks/Look/SayForBubbleBrick.m
  src/Catty/DataModel/Bricks/Look/ThinkBubbleBrick.m
  src/Catty/DataModel/Bricks/Look/ThinkForBubbleBrick.m
  src/Catty/DataModel/Bricks/Sound/SpeakAndWaitBrick.m
  src/Catty/DataModel/Bricks/Sound/SpeakBrick.m
  src/Catty/DataModel/Scripts/Script.m
  src/Catty/Extension&Delegate&Protocol/Extensions/GDataXMLElement/GDataXMLElement+CustomExtensions.m
  src/Catty/Extension&Delegate&Protocol/Extensions/NSString+Extension/NSString+CatrobatNSStringExtensions.h
  src/Catty/Extension&Delegate&Protocol/Extensions/NSString+Extension/NSString+CatrobatNSStringExtensions.m
  src/Catty/Extension&Delegate&Protocol/Extensions/NSStringExtension.swift
  src/Catty/Helpers/ImageCache/DownloadImageCache.m
  src/Catty/Helpers/ImageCache/RuntimeImageCache.m
  src/Catty/Helpers/Util/Util.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Scripts/Script+CBXMLHandler.m
  src/Catty/Parser&Serialializer/Old Parser/ProjectParser.m
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainSounds/SRViewController.m
  src/Catty/ViewController/Projects/MyProjectsViewController.m
  src/Catty/Views/Custom/CreateView/CreateView.m
  src/CattyTests/Extensions/CustomExtensionsTests.m
  src/CattyTests/Extensions/NSStringExtensionTests.swift
Labels: in code review

#1371 CATTY-263 Use UserList in VariablesContainer and model classes
  src/Catty/DataModel/Bricks/Data/AddItemToUserListBrick.h
  src/Catty/DataModel/Bricks/Data/AddItemToUserListBrick.m
  src/Catty/DataModel/Bricks/Data/DeleteItemOfUserListBrick.h
  src/Catty/DataModel/Bricks/Data/DeleteItemOfUserListBrick.m
  src/Catty/DataModel/Bricks/Data/InsertItemIntoUserListBrick.h
  src/Catty/DataModel/Bricks/Data/InsertItemIntoUserListBrick.m
  src/Catty/DataModel/Bricks/Data/ReplaceItemInUserListBrick.h
  src/Catty/DataModel/Bricks/Data/ReplaceItemInUserListBrick.m
  src/Catty/DataModel/Project/Project.m
  src/Catty/DataModel/UserData/UserVariable.swift
  src/Catty/DataModel/VariablesContainer/VariablesContainer.h
  src/Catty/DataModel/VariablesContainer/VariablesContainer.m
  src/Catty/Extension&Delegate&Protocol/Extensions/BrickExtension.swift
  src/Catty/Extension&Delegate&Protocol/Extensions/FormulaElementExtension.swift
  src/Catty/Extension&Delegate&Protocol/Protocols/Bricks/BrickData/BrickListProtocol.h
  src/Catty/FormulaEditor/InternFormulaParser.m
  src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.h
  src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
  src/Catty/Functions/List/ContainsFunction.swift
  src/Catty/Functions/List/ElementFunction.swift
  src/Catty/Functions/List/NumberOfItemsFunction.swift
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Data/AddItemToUserListBrick+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Data/DeleteItemOfUserListBrick+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Data/InsertItemIntoUserListBrick+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Data/ReplaceItemInUserListBrick+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Project/Project+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/UserData/UserVariable/UserVariable+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/VariablesContainer/VariablesContainer+CBXMLHandler.m
  src/Catty/PlayerEngine/Formula/FormulaManager+Interpreter.swift
  src/Catty/PlayerEngine/Instructions/Data/AddItemToUserListBrick+Instruction.swift
  src/Catty/PlayerEngine/Instructions/Data/DeleteItemOfUserListBrick+Instruction.swift
  src/Catty/PlayerEngine/Instructions/Data/InsertItemIntoUserListBrick+Instruction.swift
  src/Catty/PlayerEngine/Instructions/Data/ReplaceItemInUserListBrick+Instruction.swift
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellListData.m
  src/CattyTests/Bricks/BrickExtensionTests.swift
  src/CattyTests/Bricks/DeleteItemOfUserListBrickTests.swift
  src/CattyTests/Bricks/InsertItemIntoUserListBrickTests.swift
  src/CattyTests/Bricks/ReplaceItemInUserListBrickTests.swift
  src/CattyTests/DataModel/UserVariableTests.swift
  src/CattyTests/DataModel/VariablesContainerTest.swift
  src/CattyTests/Formula/FormulaElementTest.swift
  src/CattyTests/Parser & Serialization/Abstract/XMLAbstractTest.swift
  src/CattyTests/Parser & Serialization/UserListXMLHandlerTests.m
  src/CattyTests/PlayerEngine/Formula/FormulaManagerInterpreterTests.swift
  src/CattyTests/PlayerEngine/Functions/List/ContainsFunctionTest.swift
  src/CattyTests/PlayerEngine/Functions/List/ElementFunctionTest.swift
  src/CattyTests/PlayerEngine/Functions/List/NumberOfItemsFunctionTest.swift
  src/CattyTests/Project/ProjectTests.swift
  src/CattyTests/UserListFunctionsTest.swift
  src/CattyTests/ViewController/FormulaEditorViewControllerTests.swift
  src/CattyTests/Views/BrickCells/Data/BrickCellListDataTests.swift
  src/CattyTests/Views/BrickCells/Data/BrickCellVariableDataTests.swift
Labels: code review passed

#1370 CATTY-259 Add extension for Util
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/Header/Header.m
  src/Catty/Extension&Delegate&Protocol/Extensions/UIDeviceExtension.swift
  src/Catty/Helpers/Util/Util.h
  src/Catty/Helpers/Util/Util.m
  src/Catty/Helpers/Util/Util.swift
  src/Catty/Parser&Serialializer/New Parser & Serializer/Parser/CBXMLParser.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/Parser/Context/CBXMLParserContext.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Header/Header+CBXMLHandler.m
  src/CattyTests/Utils/UtilTests.swift
Labels: code review passed

#1375 CATTY-277 Implement PenDownBrick
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/Bricks/Pen/PenDownBrick.swift
  src/Catty/Defines/LanguageTranslationDefines.h
  src/Catty/Defines/LanguageTranslationDefinesSwift.swift
  src/Catty/Defines/UIDefines.h
  src/Catty/Extension&Delegate&Protocol/Extensions/UIColor+Extension/UIColor+CatrobatUIColorExtensions.swift
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Pen/PenDownBrick+CBXMLHandler.swift
  src/Catty/PlayerEngine/DataModel/CBSpriteNode/CBSpriteNode.swift
  src/Catty/PlayerEngine/Instructions/Pen/PenDownBrick+Instruction.swift
  src/Catty/Resources/Localization/en.lproj/Localizable.strings
  src/Catty/Setup/CatrobatSetup+Bricks.swift
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/Pen/PenDownBrickCell.swift
  src/CattyTests/Bricks/PenDownBrickTests.swift
  src/CattyTests/Parser & Serialization/CatrobatLanguage0.991/XMLSerializerTests/Unit Tests/XMLSerializerTests.swift
  src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0991.xml
  src/CattyTests/Scene/CBSpriteNodePenExtensionTests.swift
  src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift
Labels: code review passed

#1377 CATTY-306 Add additional tests for VariablesContainer
  src/Catty/DataModel/VariablesContainer/VariablesContainer.m
  src/CattyTests/DataModel/VariablesContainerTest.swift
Labels: in code review

#1378 CATTY-247 MOD moved FormulaMock to other folder
  src/Catty.xcodeproj/project.pbxproj
  src/CattyTests/Mocks/FormulaMock.swift
Labels: code review pending

#1390 CATTY-321 Add Swift extension for UserDataContainer
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/VariablesContainer/UserDataContainer.h
  src/Catty/DataModel/VariablesContainer/UserDataContainer.m
  src/Catty/Extension&Delegate&Protocol/Extensions/UserDataExtension.swift
  src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
  src/Catty/PlayerEngine/Scene/CBScene.swift
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
  src/CattyTests/DataModel/UserDataContainerTest.swift
  src/CattyTests/Project/ProjectTests.swift
Labels: in code review

#1394 CATTY-322 Add remove methods for SynchronizedArray when initialized with UserData
  src/Catty/DataModel/Array/SynchronizedArray.swift
  src/CattyTests/DataModel/SynchronizedArrayTests.swift
Labels: code review passed

#1396 CATTY-325 Wrong serialization for PenClearBrick
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Pen/PenClearBrick+CBXMLHandler.swift
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Scripts/Script+CBXMLHandler.m
  src/CattyTests/Resources/ParserTests/Custom/ValidProjectAllBricks/ValidProjectAllBricks0991.xml
Labels: code review pending

#1391 CATTY-217 Disable loops and nested Bricks
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController+Disable.swift
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
  src/CattyTests/ViewController/ScriptCollectionViewControllerDisableTests.swift
Labels: code review passed

#1397 CATTY-323 Add methods to Swift extension for UserDataContainer
  src/Catty/DataModel/Bricks/Data/AddItemToUserListBrick.m
  src/Catty/DataModel/Bricks/Data/ChangeVariableBrick.m
  src/Catty/DataModel/Bricks/Data/DeleteItemOfUserListBrick.m
  src/Catty/DataModel/Bricks/Data/HideTextBrick.m
  src/Catty/DataModel/Bricks/Data/InsertItemIntoUserListBrick.m
  src/Catty/DataModel/Bricks/Data/ReplaceItemInUserListBrick.m
  src/Catty/DataModel/Bricks/Data/SetVariableBrick.m
  src/Catty/DataModel/Bricks/Data/ShowTextBrick.m
  src/Catty/DataModel/Project/Project.m
  src/Catty/DataModel/VariablesContainer/UserDataContainer.h
  src/Catty/DataModel/VariablesContainer/UserDataContainer.m
  src/Catty/Extension&Delegate&Protocol/Extensions/UserDataExtension.swift
  src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellListData.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellVariableData.m
  src/CattyTests/DataModel/UserDataContainerTest.swift
  src/CattyTests/Parser & Serialization/CatrobatLanguage0.95/XMLParserTests/Unit Tests/XMLParserUserVariableTests095.swift
  src/CattyTests/Project/ProjectTests.swift
Labels: in code review

#1368 Catty - 303 Incorrect height for "End of (Repeat) Loop" Brick
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/Control/LoopEndBrickCell.m
Labels: in code review
