Repository Catrobat/Catty, pull requests merged in 2020-09, with the labels that each got.

#1254 CATTY-101: Open project from URL
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataStructures/JSON/StoreProject.swift
  src/Catty/Extension&Delegate&Protocol/Extensions/CatrobatTableViewControllerExtension.swift
  src/Catty/Pocket Code.entitlements
  src/Catty/Storyboard+XIB/iPhone.storyboard
  src/Catty/Supporting Files/AppDelegate.swift
  src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.h
  src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
  src/Catty/ViewController/Download/ChartProjects/ChartProjectsStoreViewController.swift
  src/Catty/ViewController/Download/FeaturedProjects/FeaturedProjectsStoreTableViewController.swift
  src/Catty/ViewController/Download/SearchStore/SearchStoreViewController.swift
  src/CattyTests/CatrobatTableViewControllerExtensionTests.swift
  src/CattyTests/DataModel/StoreProjectTests.swift
  src/CattyTests/Mocks/CatrobatTableViewControllerMock.swift
  src/CattyTests/Mocks/StoreProjectDownloaderMock.swift
Labels: code review passed

#1474 Catty 413 refactor uservariable+cbxmlhandler swift
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/UserData/UserVariable.swift
  src/Catty/Parser&Serialializer/New Parser & Serializer/Helper/CBXMLParserHelper.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/Helper/CBXMLValidator.h
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Data/ChangeVariableBrick+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Data/HideTextBrick+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Data/SetVariableBrick+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Data/ShowTextBrick+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/UserData/UserList/UserList+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/UserData/UserVariable/UserVariable+CBXMLHandler.h
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/UserData/UserVariable/UserVariable+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/UserData/UserVariable/UserVariable+CBXMLHandler.swift
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/VariablesContainer/UserDataContainer+CBXMLHandler.m
  src/Catty/Supporting Files/Catty-Bridging-Header.h
Labels: in code review

#1374 CATTY-49 Project can't be closed
  src/Catty/Helpers/BrickHelpers/CameraPreviewHandler.h
  src/Catty/Helpers/BrickHelpers/CameraPreviewHandler.m
  src/Catty/PlayerEngine/Sensors/Camera/FaceDetectionManager.swift
  src/CattyTests/Bricks/ChooseCameraBrickTests.swift
Labels: code review passed

#1481 CATTY-417 Add support for landscapeMode on 32-bit systems
  src/Catty/Parser&Serialializer/New Parser & Serializer/Helper/CBXMLParserHelper.m
Labels: code review passed

#1476 CATTY-334 Enable User to choose orientation when adding project
  src/Catty/DataModel/Project/Project.h
  src/Catty/DataModel/Project/Project.m
  src/Catty/Defines/LanguageTranslationDefines.h
  src/Catty/Defines/LanguageTranslationDefinesSwift.swift
  src/Catty/Resources/Localization/de.lproj/Localizable.strings
  src/Catty/Resources/Localization/en.lproj/Localizable.strings
  src/Catty/ViewController/Continue&New/SceneTableViewController.m
  src/CattyTests/Project/ProjectTests.swift
  src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift
  src/CattyUITests/MyFirstProjectTests.swift
  src/CattyUITests/Protocol/UITestProtocol.swift
Labels: code review pending
