Repository Catrobat/Catty, pull requests merged in 2020-04, with the labels that each got.

#1277 CATTY-189 Crash during selecting image in Paint
  src/Catty/PocketPaint/Helper/ImagePicker.m
Labels: code review passed

#1279 CATTY-106 Margin for BrickSelectionViewController
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickCategoryViewController.m
Labels: code review passed

#1262 CATTY-175 use error message authentication failed for non existing user
  src/Catty/ViewController/Upload/LoginViewController.m
  src/CattyTests/Utils/LoginViewControllerTests.swift
Labels: code review pending

#1266 CATTY-120 Parameter fields for Bricks
  src/Catty UITests/BrickCellTests.swift
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellFormulaData.m
Labels: code review pending

#1243 CATTY-10 add cancel button for PickerViewer
  src/Catty UITests/ScriptCollectionView/BrickCellPickerViewerTest.swift
  src/Catty UITests/ScriptCollectionView/ScriptCollectionVCTests.swift
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Extension&Delegate&Protocol/Protocols/Bricks/BrickCellDataProtocol.h
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellListData.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellLookData.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellMessageData.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellObjectData.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellPhiroIfSensorData.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellPhiroLightData.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellPhiroMotorData.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellPhiroToneData.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellSoundData.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellStaticChoiceData.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellVariableData.m
  src/Catty/Views/Custom/ComboBox/BSKeyboardControls.h
  src/Catty/Views/Custom/ComboBox/BSKeyboardControls.m
  src/Catty/Views/Custom/ComboBox/iOSCombobox.h
  src/Catty/Views/Custom/ComboBox/iOSCombobox.m
Labels: code review passed

#1286 Catty-200 Remove deprecated properties of GlideToBrick
  src/Catty/DataModel/Bricks/Motion/GlideToBrick.h
  src/Catty/DataModel/Bricks/Motion/GlideToBrick.m
Labels: code review passed

#1285 CATTY-186 Regular expression
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Functions/Text/RegularExpressionFunction.swift
  src/Catty/Setup/CatrobatSetup+Functions.swift
  src/CattyTests/PlayerEngine/Functions/Text/RegularExpressionFunctionTest.swift
Labels: code review passed

#1280 CATTY-159 Move plist files
  src/Catty UITests/ScriptCollectionView/BrickCellTests.swift
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Supporting Files/App-Info.plist
  src/Catty/Supporting Files/App-Prefix.pch
  src/Catty/Supporting Files/AppDelegate.h
  src/Catty/Supporting Files/AppDelegate.m
  src/Catty/Supporting Files/Catty-Bridging-Header.h
  src/Catty/Supporting Files/Logger/LoggerProperties.plist
  src/Catty/Supporting Files/Logger/Swell.plist
  src/Catty/Supporting Files/main.m
  src/CattyTests/Bricks/BrickMutableCopyTests.swift
  src/fastlane/Fastfile
Labels: code review passed

#1293 CATTY-187 Fix implicit return violations
  src/Catty/Functions/Text/RegularExpressionFunction.swift
Labels: code review pending

#1294 CATTY-212 Introduce GitHub Action for SwiftLint
  .github/workflows/swiftlint.yml
Labels: code review pending

#1297 Catty-166: SetLookBrick in "My first project"
  src/Catty/Resources/My first project.catrobat
Labels: code review passed

#1299 CATTY-211 Add regular expression to XML
  src/CattyTests/Resources/ParserTests/Custom/Misc/ValidFormulaList.xml
Labels: back in dev

#1291 CATTY-154 Extend StoreProjectDownloader
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/ViewController/Download/StoreProjectDownloader.swift
  src/CattyTests/Download/Fixtures/StoreProjectDownloader.downloadProject.fail.request.json
  src/CattyTests/Download/Fixtures/StoreProjectDownloader.downloadProject.success.json
  src/CattyTests/Download/StoreProjectsDownloaderTests.swift
  src/CattyTests/Mocks/StoreProjectDownloaderMock.swift
  src/CattyTests/Mocks/URLSessionMock.swift
Labels: code review passed

#1288 CATTY-195 Add non-fatal reports for Crashlytics (projects fetch)
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Extension&Delegate&Protocol/Extensions/Notification/NotificationExtension.swift
  src/Catty/Setup/Firebase/AppDelegateFirebaseExtension.swift
  src/Catty/ViewController/Download/StoreProjectDownloader.swift
  src/CattyTests/Download/StoreProjectsDownloaderTests.swift
  src/CattyTests/Setup/Firebase/FirebaseCrashlyticsSetupTests.swift
  src/CattyTests/Utils/NimbleMatcher.swift
Labels: code review passed

#1276 CATTY-168 Convert SettingsTableViewController to Swift
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Supporting Files/Catty-Bridging-Header.h
  src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
  src/Catty/ViewController/CatrobatTableViewController/SettingsTableViewController.h
  src/Catty/ViewController/CatrobatTableViewController/SettingsTableViewController.m
  src/Catty/ViewController/CatrobatTableViewController/SettingsTableViewController.swift
  src/CattyTests/CattyTests-Bridging-Header.h
Labels: code review passed

#1302 CATTY-216 Move todo warnings from SwiftLint to Xcode
  .github/workflows/swiftlint.yml
  src/Catty.xcodeproj/project.pbxproj
  src/RunScripts/.swiftlint.yml
Labels: code review pending

#1303 Catty 193 Unusual Draw-Tool Behavior
  src/Catty/PocketPaint/Tools/DrawTool.m
Labels: code review passed

#1268 Catty-104 Chromaprint warnings
  src/CattyTests/Lib/Chromaprint/libchromaprint.a
Labels: code review pending

#1298 CATTY-202 Add test for "single number formula"
  src/CattyTests/Formula/FormulaElementTest.swift
Labels: code review pending

#1311 CATTY-219 add commentedOut tags to default project
  src/Catty/Resources/My first project.catrobat
Labels: code review passed

#1304 Catty-204: Add tests for mutable copy (part 1)
  src/CattyTests/Bricks/ChangeBrightnessByNBrickTests.swift
  src/CattyTests/Bricks/ChangeColorByNBrickTests.swift
  src/CattyTests/Bricks/ChangeSizeByNBrickTests.swift
  src/CattyTests/Bricks/ChangeTransparencyByNBrickTests.swift
  src/CattyTests/Bricks/ChangeVariableBrickTests.swift
  src/CattyTests/Bricks/ChooseCameraBrickTests.swift
  src/CattyTests/Bricks/ClearGraphicEffectBrickTests.swift
  src/CattyTests/Bricks/ComeToFrontBrickTests.swift
  src/CattyTests/Bricks/DeleteItemOfUserListBrickTests.swift
Labels: code review passed

#1306 CATTY-213 Merge UI tests for "Brick cell"
  src/Catty UITests/ScriptCollectionView/BrickCellPickerViewerTest.swift
Labels: code review passed

#1317 CATTY-224 Rename UI tests
  src/Catty.xcodeproj/project.pbxproj
  src/CattyUITests/BackgroundsTests.swift
  src/CattyUITests/CreateProjectTests.swift
  src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift
  src/CattyUITests/Extensions/XCUIElement+staticTexts.swift
  src/CattyUITests/Info.plist
  src/CattyUITests/LooksTVCTests.swift
  src/CattyUITests/MyFirstProjectTests.swift
  src/CattyUITests/ObjectTVCTests.swift
  src/CattyUITests/PocketCodeMainScreenTests.swift
  src/CattyUITests/ProjectTVCTests.swift
  src/CattyUITests/ProjectsTVCTests.swift
  src/CattyUITests/Protocol/UITestProtocol.swift
  src/CattyUITests/ScenePresenterVCTests.swift
  src/CattyUITests/ScriptCollectionView/BrickCellPickerViewerTest.swift
  src/CattyUITests/ScriptCollectionView/BrickCellTests.swift
  src/CattyUITests/ScriptCollectionView/ScriptCollectionVCTests.swift
  src/CattyUITests/SettingsTVCTests.swift
  src/CattyUITests/SoundsTVCTests.swift
  src/CattyUITests/VariablesTests.swift
  src/RunScripts/.swiftlint.auto.yml
  src/RunScripts/.swiftlint.yml
  src/RunScripts/synchronize-localization.py
Labels: code review passed

#1318 CATTY-227 Change bundle identifier for tests
  src/Catty.xcodeproj/project.pbxproj
Labels: code review pending

#1292 Catty-77: Migrate UIWebView to WKWebView
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Helpers/FileManager/CBFileManager.h
  src/Catty/Storyboard+XIB/iPhone.storyboard
  src/Catty/ViewController/Download/ProjectDetailStoreViewController.h
  src/Catty/ViewController/Help/HelpWebViewController.swift
  src/CattyTests/ViewController/HelpWebViewControllerTests.swift
Labels: code review passed

#1323 Catty-231: Added tests for VariablesContainer (part 2)
  src/CattyTests/DataModel/VariablesContainerTest.swift
Labels: in code review

#1324 CATTY-233 Add tests for VariableContainer (part 4)
  src/CattyTests/DataModel/VariablesContainerTest.swift
Labels: in code review

#1326 CATTY-196 Add non-fatal reports for Crashlytics (media library)
  src/Catty/Extension&Delegate&Protocol/Extensions/Notification/NotificationExtension.swift
  src/Catty/Setup/Firebase/AppDelegateFirebaseExtension.swift
  src/Catty/ViewController/MediaLibrary/MediaLibraryDownloader.swift
  src/CattyTests/MediaLibrary/MediaLibraryDownloaderTests.swift
  src/CattyTests/Setup/Firebase/FirebaseCrashlyticsSetupTests.swift
Labels: code review passed

#1325 CATTY-235 Add tests for VariableContainer (part 5)
  src/CattyTests/DataModel/VariablesContainerTest.swift
Labels: in code review

#1327 Catty-232: Added tests for VariablesContainer (part 3)
  src/CattyTests/DataModel/VariablesContainerTest.swift
Labels: code review passed

#1332 JENKINS-370: Move Job Paramater for Catty Release Job to Jenkinsfile
  Jenkinsfile.release
Labels: in code review

#1278 CATTY-90 removed last border on main menue screen
  src/Catty/Helpers/Util/TableUtil.h
  src/Catty/Helpers/Util/TableUtil.m
  src/Catty/Helpers/Util/Util.h
  src/Catty/Helpers/Util/Util.m
  src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
Labels: code review passed
