Repository Catrobat/Catty, pull requests merged in 2020-03, with the labels that each got.

#1256 CATTY-174 Change default value of camera/flashlight brick
  src/Catty/DataModel/Bricks/IO/FlashBrick.m
Labels: code review passed

#1259 Catty-180 Extend pull request template
  .github/pull_request_template.md
Labels: code review pending

#1257 CATTY-126 add increasing number to downloaded projects with same name
  src/Catty/ViewController/Download/ProjectDetailStoreViewController.m
  src/CattyTests/FileManager/CBFileManagerTests.swift
Labels: code review passed

#1208 CATTY-109 Convert FormulaTest from ObjC to Swift
  src/Catty.xcodeproj/project.pbxproj
  src/CattyTests/Formula/FormulaTest.m
  src/CattyTests/Formula/FormulaTest.swift
Labels: code review passed

#1263 CATTY-182 Upgrade to AudioKit 4.9.4
  src/Cartfile
  src/Cartfile.resolved
Labels: code review passed

#1255 CATTY-153 extend isVarOrListBeingUsed for lists
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Catty-Bridging-Header.h
  src/Catty/Extension&Delegate&Protocol/Protocols/Bricks/BrickData/BrickListProtocol.h
  src/Catty/FormulaEditor/Helper/Brick+UserVariable.m
  src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
  src/CattyTests/Bricks/BrickWithUserVariableTests.swift
Labels: back in dev

#1261 CATTY-149 Page indicator missing for Brick selection
  src/Catty/Extension&Delegate&Protocol/Extensions/UIColor+Extension/UIColor+CatrobatUIColorExtensions.swift
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickCategoryViewController.m
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickSelectionViewController.m
Labels: code review passed

#1274 CATTY-176 Crash during creating new project.
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m
  src/CattyTests/FileManager/CBFileManagerTests.swift
Labels: code review passed

#1267 CATTY-181 Cancel button nearly invisible on image upload
  src/Catty/AppDelegate.m
  src/Catty/PocketPaint/Helper/ImagePicker.m
  src/Catty/PocketPaint/ViewController/PaintViewController.m
  src/Catty/ViewController/BluetoothDeviceSelection/BluetoothPopupVC.swift
  src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m
Labels: code review passed
