Repository Catrobat/Catty, pull requests merged in 2020-07, with the labels that each got.

#1402 CATTY-324 Get all objects and use them in UserDataContainer
  src/Catty/DataModel/Project/Project.h
  src/Catty/DataModel/Project/Project.m
  src/Catty/Extension&Delegate&Protocol/Extensions/Project+Extension/Project+CustomExtensions.m
  src/Catty/Extension&Delegate&Protocol/Extensions/UserDataExtension.swift
  src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
  src/Catty/Helpers/Util/Util.m
  src/CattyTests/DataModel/UserDataContainerTest.swift
  src/CattyTests/Project/ProjectTests.swift
Labels: code review passed

#1400 CATTY-330 Implement StoreProjectUploader
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Store/StoreProjectDownloader.swift
  src/Catty/Store/StoreProjectUploader.swift
  src/CattyTests/Mocks/CBFileManagerMock.swift
  src/CattyTests/Mocks/URLSessionMock.swift
  src/CattyTests/Store/Download/ChartProjectsStoreDataSourceTests.swift
  src/CattyTests/Store/Download/FeaturedProjectsStoreDataSourceTests.swift
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.downloadProject.fail.request.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.downloadProject.success.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchFeaturedProjects.IntegerId.success.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchFeaturedProjects.fail.parse.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchFeaturedProjects.fail.request.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchFeaturedProjects.success.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchMostDownloadedProjects.IntegerId.success.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchMostDownloadedProjects.fail.parse.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchMostDownloadedProjects.fail.request.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchMostDownloadedProjects.success.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchMostRecentProjects.IntegerId.success.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchMostRecentProjects.fail.parse.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchMostRecentProjects.fail.request.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchMostRecentProjects.success.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchMostViewedProjects.IntegerId.success.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchMostViewedProjects.fail.parse.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchMostViewedProjects.fail.request.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchMostViewedProjects.success.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchProjectDetails.IntegerId.success.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchProjectDetails.fail.request.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchProjectDetails.success.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.fetchSearchProjects.fail.parse.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.searchProjects.IntegerId.success.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.searchProjects.fail.request.json
  src/CattyTests/Store/Download/Fixtures/StoreProjectDownloader.searchProjects.success.json
  src/CattyTests/Store/Download/SearchStoreDataSourceTests.swift
  src/CattyTests/Store/Download/StoreProjectsDownloaderTests.swift
  src/CattyTests/Store/Upload/Fixture/StoreProjectDownloader.uploadProject.fail.authentication.json
  src/CattyTests/Store/Upload/Fixture/StoreProjectDownloader.uploadProject.fail.invalidChecksum.json
  src/CattyTests/Store/Upload/Fixture/StoreProjectDownloader.uploadProject.fail.invalidProject.json
  src/CattyTests/Store/Upload/Fixture/StoreProjectUpload.uploadProject.fail.invalidBody.json
  src/CattyTests/Store/Upload/Fixture/StoreProjectUpload.uploadProject.success.json
  src/CattyTests/Store/Upload/StoreProjectUploaderTests.swift
Labels: in code review

#1389 CATTY-317 Wrong initial position for Pen
  src/Catty/Extension&Delegate&Protocol/Extensions/SpriteNode/CBSpriteNodePenExtension.swift
  src/Catty/PlayerEngine/Instructions/Motion/MoveNStepsBrick+Instruction.swift
  src/Catty/PlayerEngine/Instructions/Pen/PenDownBrick+Instruction.swift
  src/Catty/PlayerEngine/Instructions/Pen/PenUpBrick+Instruction.swift
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/Pen/PenClearBrick+Instruction.swift
  src/CattyTests/Bricks/PenClearBrickTests.swift
  src/CattyTests/Bricks/PenDownBrickTests.swift
  src/CattyTests/Bricks/PenUpBrickTests.swift
Labels: code review passed, in code review

#1398 CATTY-331 Initial constuction of possible parameterization
  src/Catty/Parser&Serialializer/New Parser & Serializer/Helper/CBXMLSerializerHelper.h
  src/Catty/Parser&Serialializer/New Parser & Serializer/Helper/CBXMLSerializerHelper.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Look/SetBackgroundBrick+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Look/SetLookBrick+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Sound/PlaySoundAndWaitBrick+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Sound/PlaySoundBrick+CBXMLHandler.m
  src/CattyTests/Parser & Serialization/Helper/CBXMLParserHelperTests.swift
Labels: code review pending

#1392 CATTY-304 Add preview image for last used project
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Extension&Delegate&Protocol/Extensions/CBFileManagerExtension.swift
  src/Catty/Helpers/ImageCache/ImageCache.m
  src/Catty/Images.xcassets/Icons/continue.imageset/Icons_main_menu_continue.png
  src/Catty/Storyboard+XIB/iPhone.storyboard
  src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
  src/Catty/ViewController/Projects/MyProjectsViewController.m
  src/CattyTests/FileManager/CBFileManagerTests.swift
  src/CattyTests/Mocks/CBFileManagerMock.swift
  src/CattyTests/Mocks/RuntimeImageCacheMock.swift
Labels: in code review

#1405 CATTY-333 Use StoreProjectUploader in UploadViewController
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Defines/LanguageTranslationDefines.h
  src/Catty/Defines/LanguageTranslationDefinesSwift.swift
  src/Catty/Resources/Localization/en.lproj/Localizable.strings
  src/Catty/Store/StoreProjectUploader.swift
  src/Catty/Supporting Files/Catty-Bridging-Header.h
  src/Catty/ViewController/Upload/UploadViewController.swift
  src/CattyTests/Mocks/StoreProjectUploaderMock.swift
  src/CattyTests/Store/Upload/StoreProjectUploaderTests.swift
  src/CattyTests/ViewController/UploadViewControllerTests.swift
  src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift
Labels: in code review

#1413 CATTY-362 Add additional XML for testing UserVariable parsing
  src/Catty.xcodeproj/project.pbxproj
  src/CattyTests/Parser & Serialization/CatrobatLanguage0.93/BlackBox Tests/XMLParserBlackBoxTests093.swift
  src/CattyTests/Resources/ParserTests/Custom/Data/UserVariables_093.xml
  src/CattyTests/Resources/ParserTests/Custom/Data/UserVariables_0991.xml
Labels: code review passed

#1412 CATTY-315 Text can not be joined with lists
  src/Catty/Functions/Protocols/Function.swift
  src/CattyTests/PlayerEngine/Functions/Text/JoinFunctionTest.swift
Labels: code review passed

#1372 CATTY-296 Fatal crash in audio player
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/PlayerEngine/AudioEngine/AudioEngine.swift
  src/Catty/PlayerEngine/AudioEngine/AudioEngineHelper.swift
  src/Catty/PlayerEngine/AudioEngine/AudioManager.h
  src/Catty/PlayerEngine/AudioEngine/AudioManager.m
  src/Catty/PlayerEngine/AudioEngine/AudioPlayer.swift
  src/Catty/Supporting Files/AppDelegate.swift
  src/Catty/ViewController/Scene/ScenePresenterViewController.m
  src/CattyTests/AppDelegateTests.swift
  src/CattyTests/Mocks/ScenePresenterViewControllerSpy.swift
  src/CattyTests/PlayerEngine/AudioEngine/Mocks/AudioEngineHelperSpy.swift
  src/CattyTests/ViewController/Scene/ScenePresenterViewControllerTest.swift
Labels: in code review

#1406 CATTY-327 Inclination Sensor behaviour landscape mode
  src/Catty/PlayerEngine/Sensors/Motion/InclinationXSensor.swift
  src/Catty/PlayerEngine/Sensors/Motion/InclinationYSensor.swift
  src/CattyTests/PlayerEngine/Sensors/Motion/InclinationXSensorTest.swift
  src/CattyTests/PlayerEngine/Sensors/Motion/InclinationYSensorTest.swift
Labels: code review passed

#1403 CATTY-326 Accelerator Sensor behaviour landscape mode
  src/Catty/PlayerEngine/Sensors/Motion/AccelerationXSensor.swift
  src/Catty/PlayerEngine/Sensors/Motion/AccelerationYSensor.swift
  src/CattyTests/PlayerEngine/Sensors/Motion/AccelerationXSensorTest.swift
  src/CattyTests/PlayerEngine/Sensors/Motion/AccelerationYSensorTest.swift
Labels: code review passed

#1420 CATTY-329 Compass Direction Sensor behaviour landscape mode
  src/Catty/PlayerEngine/Sensors/Heading/CompassDirectionSensor.swift
  src/CattyTests/PlayerEngine/Sensors/Heading/CompassDirectionSensorTest.swift
Labels: code review passed

#1424 Catty-366 Text representation of lists
  src/Catty/DataModel/UserData/UserList.swift
  src/Catty/Functions/Protocols/Function.swift
  src/Catty/PlayerEngine/Formula/FormulaManager+Interpreter.swift
  src/CattyTests/DataModel/UserListTest.swift
Labels: code review pending

#1411 CATTY-346 Redesign Upload ViewController
  src/Catty/Defines/LanguageTranslationDefines.h
  src/Catty/Defines/LanguageTranslationDefinesSwift.swift
  src/Catty/Resources/Localization/en.lproj/Localizable.strings
  src/Catty/Storyboard+XIB/iPhone.storyboard
  src/Catty/ViewController/Upload/UploadViewController.swift
  src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift
Labels: in code review

#1438 CATTY-381 Program closes unexpectedly when saving image to camera roll
  src/Catty/PocketPaint/ViewController/PaintViewController.m
Labels: code review passed, hotfix

#1437 CATTY-382 Fix md5 for large NSData
  src/Catty/Extension&Delegate&Protocol/Extensions/NSDataExtension.swift
  src/CattyTests/Extensions/NSDataExtensionTests.swift
Labels: code review pending, hotfix

#1427 CATTY-267 Delete the commented code
  src/Catty/PlayerEngine/DataModel/CBSpriteNode/CBSpriteNode.swift
Labels: code review passed

#1431 CATTY-255 rename Double+Extensions to DoubleExtension.swift
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Extension&Delegate&Protocol/Extensions/DoubleExtension.swift
Labels: code review passed

#1430 CATTY-297 move VariableTests and ListTests to ScriptCollectionView
  src/Catty.xcodeproj/project.pbxproj
  src/CattyUITests/ScriptCollectionView/ListTests.swift
  src/CattyUITests/ScriptCollectionView/VariableTests.swift
Labels: code review passed

#1433 CATTY-34: Project with Arduino Brick not starting
  src/Catty/ViewController/Scene/ScenePresenterViewController+Resources.swift
Labels: code review passed

#1428 CATTY-253 Rename UIColor+Extension and remove folder
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Extension&Delegate&Protocol/Extensions/UIColorExtension.swift
Labels: code review passed

#1429 CATTY-300 Rename CBSpriteNode+Sensor and move to SpriteNode
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Extension&Delegate&Protocol/Extensions/SpriteNode/CBSpriteNodeSensorExtension.swift
Labels: code review passed

#1414 CATTY-348 Invalid behaviour of pen with PlaceAt bricks
  src/Catty/DataModel/Array/SynchronizedArray.swift
  src/Catty/DataModel/Configuration/PenConfiguration.swift
  src/Catty/Extension&Delegate&Protocol/Extensions/SpriteNode/CBSpriteNodePenExtension.swift
  src/Catty/Extension&Delegate&Protocol/Extensions/SpriteNode/CBSpriteNodeSensorExtension.swift
  src/Catty/PlayerEngine/DataModel/CBSpriteNode/CBSpriteNode.swift
  src/Catty/PlayerEngine/Instructions/Pen/PenClearBrick+Instruction.swift
  src/Catty/PlayerEngine/Instructions/Pen/PenDownBrick+Instruction.swift
  src/Catty/PlayerEngine/Instructions/Pen/PenUpBrick+Instruction.swift
  src/CattyTests/Bricks/PenClearBrickTests.swift
  src/CattyTests/Bricks/PenDownBrickTests.swift
  src/CattyTests/Bricks/PenUpBrickTests.swift
  src/CattyTests/DataModel/SynchronizedArrayTests.swift
  src/CattyTests/Scene/CBSpriteNodePenExtensionTests.swift
Labels: code review passed

#1404 CATTY-332 Add UserDataContainer to SpriteObject
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/Project/Project.m
  src/Catty/DataModel/SpriteObject/SpriteObject.h
  src/Catty/DataModel/SpriteObject/SpriteObject.m
  src/Catty/DataModel/VariablesContainer/UserDataContainer.h
  src/Catty/DataModel/VariablesContainer/UserDataContainer.m
  src/Catty/Extension&Delegate&Protocol/Extensions/UserDataContainerExtension.swift
  src/Catty/FormulaEditor/InternFormulaParser.m
  src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/Context/Abstract/CBXMLAbstractContext.h
  src/Catty/Parser&Serialializer/New Parser & Serializer/Context/Abstract/CBXMLAbstractContext.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/Parser/CBXMLParser.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/Parser/Context/CBXMLParserContext.h
  src/Catty/Parser&Serialializer/New Parser & Serializer/Parser/Context/CBXMLParserContext.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/Serializer/CBXMLSerializer.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/Serializer/Context/CBXMLSerializerContext.h
  src/Catty/Parser&Serialializer/New Parser & Serializer/Serializer/Context/CBXMLSerializerContext.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Formula/FormulaElement+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Project/Project+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/SpriteObject/SpriteObject+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/UserData/UserList/UserList+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/UserData/UserVariable/UserVariable+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/VariablesContainer/UserDataContainer+CBXMLHandler.h
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/VariablesContainer/UserDataContainer+CBXMLHandler.m
  src/Catty/Parser&Serialializer/Old Parser/ProjectParser.m
  src/Catty/PlayerEngine/Formula/FormulaManager+Interpreter.swift
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
  src/CattyTests/Bricks/BrickExtensionTests.swift
  src/CattyTests/Bricks/DeleteItemOfUserListBrickTests.swift
  src/CattyTests/Bricks/InsertItemIntoUserListBrickTests.swift
  src/CattyTests/Bricks/ReplaceItemInUserListBrickTests.swift
  src/CattyTests/Bricks/WaitUntilBrickTests.swift
  src/CattyTests/DataModel/UserDataContainerTest.swift
  src/CattyTests/Parser & Serialization/Abstract/XMLAbstractTest.swift
  src/CattyTests/Parser & Serialization/CatrobatLanguage0.93/Unit Tests/XMLParserBrickTests093.swift
  src/CattyTests/Parser & Serialization/CatrobatLanguage0.93/Unit Tests/XMLParserFormulaTests093.swift
  src/CattyTests/Parser & Serialization/CatrobatLanguage0.93/Unit Tests/XMLParserHeaderTests093.swift
  src/CattyTests/Parser & Serialization/CatrobatLanguage0.93/Unit Tests/XMLParserObjectTests093.swift
  src/CattyTests/Parser & Serialization/CatrobatLanguage0.95/XMLParserTests/Unit Tests/XMLParserBrickTests095.swift
  src/CattyTests/Parser & Serialization/CatrobatLanguage0.95/XMLParserTests/Unit Tests/XMLParserFormulaTests095.swift
  src/CattyTests/Parser & Serialization/CatrobatLanguage0.95/XMLParserTests/Unit Tests/XMLParserHeaderTests095.swift
  src/CattyTests/Parser & Serialization/CatrobatLanguage0.95/XMLParserTests/Unit Tests/XMLParserObjectTests095.swift
  src/CattyTests/Parser & Serialization/CatrobatLanguage0.95/XMLParserTests/Unit Tests/XMLParserUserVariableTests095.swift
  src/CattyTests/Parser & Serialization/CatrobatLanguage0.991/XMLSerializerTests/Unit Tests/XMLSerializerTests.swift
  src/CattyTests/Parser & Serialization/UserListXMLHandlerTests.m
  src/CattyTests/PlayerEngine/Formula/FormulaManagerInterpreterTests.swift
  src/CattyTests/Project/ProjectTests.swift
  src/CattyTests/Resources/ParserTests/Custom/Data/UserVariables_091.xml
  src/CattyTests/Scene/SceneTests.swift
  src/CattyTests/SpriteObjectMutableCopyTests.swift
  src/CattyTests/SpriteObjectTest.swift
  src/CattyTests/UserListFunctionsTest.swift
  src/CattyTests/ViewController/FormulaEditorViewControllerTests.swift
  src/CattyTests/Views/BrickCells/Data/BrickCellListDataTests.swift
  src/CattyTests/Views/BrickCells/Data/BrickCellVariableDataTests.swift
Labels: in code review

#1331 Catty-163: New value overwrites most recent value for Broadcast
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/Bricks/Control/BroadcastBrick.m
  src/Catty/DataModel/Bricks/Control/BroadcastWaitBrick.m
  src/Catty/DataModel/Project/Project.h
  src/Catty/DataModel/Project/Project.m
  src/Catty/DataModel/Scripts/BroadcastScript.m
  src/Catty/Helpers/Util/Util.h
  src/Catty/Helpers/Util/Util.m
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellMessageData.m
  src/CattyTests/CattyTests-Bridging-Header.h
  src/CattyTests/Utils/UtilTests.swift
  src/CattyTests/ViewController/ScriptCollectionViewControllerTests.swift
Labels: code review passed

#1423 CATTY-368 Make PenSize dependent on screen ratio
  src/Catty/DataModel/Configuration/PenConfiguration.swift
  src/Catty/PlayerEngine/DataModel/CBSpriteNode/CBSpriteNode.swift
  src/CattyTests/PlayerEngine/CBSpriteNodeTests.swift
  src/CattyTests/Scene/PenConfigurationTests.swift
Labels: in code review

#1432 CATTY-271 delete unused segueDefines
  src/Catty/Defines/SegueDefines.h
Labels: code review passed

#1446 CATTY-388 SetColorBrick with a number is than INT-MAX crashes
  src/Catty/PlayerEngine/Sensors/Object/ColorSensor.swift
  src/CattyTests/PlayerEngine/Sensors/Object/ColorSensorTest.swift
Labels: code review passed

#1448 CATTY-208 changed error to build-warning when catrobat header is prev…
  src/RunScripts/license-validator.swift
  src/RunScripts/precompile-tests.swift
Labels: code review passed

#1447 CATTY-389 Convert UserDataContainer to Swift
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/Bricks/Data/AddItemToUserListBrick.m
  src/Catty/DataModel/Bricks/Data/DeleteItemOfUserListBrick.m
  src/Catty/DataModel/Bricks/Data/InsertItemIntoUserListBrick.m
  src/Catty/DataModel/Bricks/Data/ReplaceItemInUserListBrick.m
  src/Catty/DataModel/Formula/FormulaElement.m
  src/Catty/DataModel/Project/Project.m
  src/Catty/DataModel/SpriteObject/SpriteObject.m
  src/Catty/DataModel/UserDataContainer/UserDataContainer.swift
  src/Catty/DataModel/VariablesContainer/UserDataContainer.h
  src/Catty/DataModel/VariablesContainer/UserDataContainer.m
  src/Catty/FormulaEditor/InternFormulaParser.h
  src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.h
  src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/Context/Abstract/CBXMLAbstractContext.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/UserData/UserList/UserList+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/UserData/UserVariable/UserVariable+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/VariablesContainer/UserDataContainer+CBXMLHandler.h
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/VariablesContainer/UserDataContainer+CBXMLHandler.m
  src/Catty/Parser&Serialializer/Old Parser/ProjectParser.m
  src/Catty/Supporting Files/Catty-Bridging-Header.h
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellListData.m
  src/CattyTests/Bricks/BrickExtensionTests.swift
  src/CattyTests/Bricks/DeleteItemOfUserListBrickTests.swift
  src/CattyTests/Bricks/InsertItemIntoUserListBrickTests.swift
  src/CattyTests/Bricks/ReplaceItemInUserListBrickTests.swift
  src/CattyTests/Bricks/WaitUntilBrickTests.swift
  src/CattyTests/DataModel/UserDataContainerTest.swift
  src/CattyTests/Parser & Serialization/CatrobatLanguage0.95/XMLParserTests/Unit Tests/XMLParserBrickTests095.swift
  src/CattyTests/PlayerEngine/Formula/FormulaManagerInterpreterTests.swift
  src/CattyTests/Project/ProjectTests.swift
  src/CattyTests/Scene/SceneTests.swift
  src/CattyTests/SpriteObjectMutableCopyTests.swift
  src/CattyTests/SpriteObjectTest.swift
  src/CattyTests/UserListFunctionsTest.swift
  src/CattyTests/ViewController/FormulaEditorViewControllerTests.swift
  src/CattyTests/Views/BrickCells/Data/BrickCellListDataTests.swift
  src/CattyTests/Views/BrickCells/Data/BrickCellVariableDataTests.swift
Labels: code review passed
