Repository Catrobat/Catty, pull requests merged in 2021-03, with the labels that each got.

#1584 CATTY-386 Move loading of preview image to ProjectManager
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Extension&Delegate&Protocol/Extensions/CBFileManagerExtension.swift
  src/Catty/IO/ProjectManager.swift
  src/Catty/ViewController/CatrobatTableViewController/CatrobatTableViewController.m
  src/Catty/ViewController/Projects/MyProjectsViewController.m
  src/CattyTests/FileManager/CBFileManagerTests.swift
  src/CattyTests/FileManager/ProjectManagerTests.swift
  src/CattyTests/Mocks/CBFileManagerMock.swift
Labels: code review passed

#1578 CATTY-476 remove unused notification name defines, move used defines to NotificationExtension
  src/Catty/DataModel/Project/Project.m
  src/Catty/Defines/UIDefines.h
  src/Catty/Extension&Delegate&Protocol/Extensions/NotificationExtension.swift
  src/Catty/IO/FileManager/CBFileManager.m
  src/Catty/ViewController/BaseViewController/BaseTableViewController.m
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainSounds/SoundsTableViewController.m
  src/Catty/ViewController/Upload/UploadViewController.swift
Labels: in code review

#1603 CATTY-518: App crash when computing "direction" in FE
  src/Catty/PlayerEngine/Sensors/Object/RotationSensor.swift
  src/CattyTests/PlayerEngine/Sensors/Object/RotationSensorTest.swift
Labels: code review passed

#1612 CATTY-495 Brick selected notification fired twice
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
Labels: code review passed

#1569 CATTY-131 AudioPlayerIntegrationTests fail occasionally
  src/CattyTests/PlayerEngine/AudioEngine/IntegrationTests/AudioPlayerIntegrationTests.swift
Labels: back in dev

#1588 CATTY-509 Replace deprecated NSLog statements with custom Logger
  src/Catty/BluetoothHelper/BluetoothHelper/Components/CentralManager.swift
  src/Catty/BluetoothHelper/BluetoothHelper/Components/Peripheral.swift
  src/Catty/BluetoothHelper/BluetoothHelper/Components/Service.swift
  src/Catty/Parser&Serialializer/New Parser & Serializer/Helper/CBXMLValidator.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/VariablesContainer/UserDataContainer+CBXMLHandler.m
  src/Catty/PocketPaint/ViewController/PaintViewController.m
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickManager/BrickMoveManager.m
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainSounds/SoundsTableViewController.m
  src/Catty/ViewController/Upload/LoginViewController.m
  src/Catty/ViewController/Upload/RegisterViewController.m
  src/CattyTests/Parser & Serialization/CatrobatLanguage0.95/XMLParserTests/Unit Tests/XMLParserBrickTests095.swift
  src/CattyTests/TestHelpers/ConvertExceptionToError.m
Labels: code review passed

#1611 CATTY-521 Merging of EmbroideryStreams crashes
  src/Catty/Embroidery/EmbroideryDSTService.swift
  src/Catty/Embroidery/EmbroideryStream.swift
  src/CattyTests/Embroidery/EmbroideryDSTServiceTests.swift
  src/CattyTests/Embroidery/EmbroideryStreamTests.swift
Labels: code review passed

#1610 CATTY-522 Convert Util methods to Swift 1/3
  src/Catty/Helpers/Util/TableUtil.m
  src/Catty/Helpers/Util/Util.h
  src/Catty/Helpers/Util/Util.m
  src/Catty/Helpers/Util/Util.swift
  src/CattyTests/Utils/UtilTests.swift
Labels: code review passed

#1608 CATTY-533 UnDo a rotation of an image, it is not on the correct position
  src/Catty/PocketPaint/UndoManager/UndoManager.m
  src/Catty/Supporting Files/Catty-Bridging-Header.h
  src/CattyTests/Mocks/PaintViewControllerMock.swift
  src/CattyTests/ViewController/PaintViewControllerTests.swift
Labels: code review passed

#1605 CATTY-530 Modify Swift extension for ProjectDetailStoreViewController
  src/Catty/Extension&Delegate&Protocol/Extensions/UIViewController/ProjectDetailStoreViewControllerReportExtension.swift
  src/Catty/ViewController/Download/Details/ProjectDetailStoreViewController.h
  src/Catty/ViewController/Download/Details/ProjectDetailStoreViewController.m
  src/Catty/ViewController/Download/Details/ProjectDetailStoreViewControllerExtension.swift
  src/CattyTests/Extensions/ProjectDetailStoreViewControllerExtensionTests.swift
Labels: code review pending

#1607 Catty-532 App crash -> allow to use photo library
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainLooks/LooksTableViewController.m
Labels: code review passed

#1598 CATTY-514 Wrong Brick color for Bricks of a disabled extensions
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/Bricks/Category/BrickCategory.swift
  src/Catty/Resources/Localization/en.lproj/Localizable.strings
  src/Catty/Setup/CatrobatSetup+Bricks.swift
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/BrickCategoryOverviewController.swift
  src/CattyTests/Bricks/BrickCategoryTest.swift
  src/CattyTests/Setup/CatrobatSetupTests.swift
  src/CattyTests/ViewController/BrickCategoryOverviewControllerTests.swift
  src/CattyTests/ViewController/BrickCategoryViewControllerTests.swift
Labels: code review passed

#1609 CATTY-376 Image resolution worsens after rotating the background image
  src/Catty/PocketPaint/Tools/MirrorRotationZoomTool.m
  src/CattyTests/CattyTests-Bridging-Header.h
  src/CattyTests/Mocks/PaintViewControllerMock.swift
  src/CattyTests/ViewController/PaintViewControllerTests.swift
Labels: code review passed

#1597 CATTY-445 Variable width for Formula fields
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellFormulaData.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/BrickCell.h
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/BrickCell.m
  src/CattyTests/Views/BrickCells/Data/BrickCellFormulaDataTests.swift
Labels: code review passed

#1544 CATTY-464 Change icons of side menu
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Defines/LanguageTranslationDefines.h
  src/Catty/Defines/LanguageTranslationDefinesSwift.swift
  src/Catty/Extension&Delegate&Protocol/Extensions/UIColorExtension.swift
  src/Catty/Images.xcassets/Icons/Contents.json
  src/Catty/Images.xcassets/Icons/stage_dialog_button_aspect_ratio.imageset/Contents.json
  src/Catty/Images.xcassets/Icons/stage_dialog_button_aspect_ratio.imageset/stage_dialog_button_aspect_ratio.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_aspect_ratio.imageset/stage_icons_fullscreen-xhdpi.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_aspect_ratio_close.imageset/Contents.json
  src/Catty/Images.xcassets/Icons/stage_dialog_button_aspect_ratio_close.imageset/stage_dialog_button_aspect_ratio_close.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_aspect_ratio_pressed.imageset/Contents.json
  src/Catty/Images.xcassets/Icons/stage_dialog_button_aspect_ratio_pressed.imageset/stage_icons_fullscreen-xhdpi.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_back.imageset/Contents.json
  src/Catty/Images.xcassets/Icons/stage_dialog_button_back.imageset/stage_dialog_button_back.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_back.imageset/stage_icons_back-xhdpi.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_back_pressed.imageset/Contents.json
  src/Catty/Images.xcassets/Icons/stage_dialog_button_back_pressed.imageset/stage_icons_back-xhdpi.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_continue.imageset/Contents.json
  src/Catty/Images.xcassets/Icons/stage_dialog_button_continue.imageset/stage_dialog_button_continue.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_continue.imageset/stage_icons_continue-xhdpi.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_continue_pressed.imageset/Contents.json
  src/Catty/Images.xcassets/Icons/stage_dialog_button_continue_pressed.imageset/stage_icons_continue-xhdpi.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_restart.imageset/Contents.json
  src/Catty/Images.xcassets/Icons/stage_dialog_button_restart.imageset/stage_dialog_button_restart.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_restart.imageset/stage_icons_restart-xhdpi.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_restart_pressed.imageset/Contents.json
  src/Catty/Images.xcassets/Icons/stage_dialog_button_restart_pressed.imageset/stage_icons_restart-xhdpi.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_screenshot.imageset/Contents.json
  src/Catty/Images.xcassets/Icons/stage_dialog_button_screenshot.imageset/stage_dialog_button_screenshot.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_screenshot.imageset/stage_icons_screenshot-xhdpi.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_screenshot_pressed.imageset/stage_icons_screenshot-xhdpi.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_toggle_axis.imageset/Contents.json
  src/Catty/Images.xcassets/Icons/stage_dialog_button_toggle_axis.imageset/stage_dialog_button_toggle_axis.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_toggle_axis.imageset/stage_icons_axis-xhdpi.png
  src/Catty/Images.xcassets/Icons/stage_dialog_button_toggle_axis_pressed.imageset/Contents.json
  src/Catty/Images.xcassets/Icons/stage_dialog_button_toggle_axis_pressed.imageset/stage_icons_axis-xhdpi.png
  src/Catty/Resources/Localization/en.lproj/Localizable.strings
  src/Catty/Storyboard+XIB/SceneMenuView.xib
  src/Catty/ViewController/Stage/StagePresenterSideMenuView.swift
  src/Catty/ViewController/Stage/StagePresenterViewController.h
  src/Catty/ViewController/Stage/StagePresenterViewController.m
  src/CattyTests/ViewController/Stage/StagePresenterSideMenuViewTests.swift
  src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift
Labels: code review passed

#1620 CATTY-544 Remove duplicate build compile warning
  src/Catty.xcodeproj/project.pbxproj
Labels: code review passed

#1616 CATTY-527 Convert NextLookBrick and PreviousLookBrick to Swift
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/Bricks/Look/NextLookBrick.swift
  src/Catty/DataModel/Bricks/Look/PreviousLookBrick.m
  src/Catty/DataModel/Bricks/Look/PreviousLookBrick.swift
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Look/NextLookBrick+CBXMLHandler.h
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Look/NextLookBrick+CBXMLHandler.swift
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Look/PreviousLookBrick+CBXMLHandler.swift
  src/Catty/PlayerEngine/Instructions/Look/NextLookBrick+Instruction.swift
  src/Catty/PlayerEngine/Instructions/Look/PreviousLookBrick+Instruction.swift
  src/Catty/Supporting Files/Catty-Bridging-Header.h
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/NextLookBrickCell.h
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/NextLookBrickCell.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/NextLookBrickCell.swift
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/PreviousLookBrickCell.h
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/PreviousLookBrickCell.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/PreviousLookBrickCell.swift
  src/CattyTests/Bricks/NextLookBrickTests.swift
  src/CattyTests/Bricks/PreviousLookBrickTests.swift
Labels: code review passed

#1602 CATTY-523 Convert Util methods to Swift 2/3
  src/Catty/Extension&Delegate&Protocol/Extensions/UIViewController/CatrobatTableViewControllerExtension.swift
  src/Catty/Extension&Delegate&Protocol/Extensions/UIViewController/ProjectDetailStoreViewControllerDownloadExtension.swift
  src/Catty/Extension&Delegate&Protocol/Extensions/UIViewController/ProjectDetailStoreViewControllerReportExtension.swift
  src/Catty/Extension&Delegate&Protocol/Extensions/UIViewController/UIViewControllerExtension.swift
  src/Catty/Helpers/Bluetooth/BluetoothService.swift
  src/Catty/Helpers/Util/Util.h
  src/Catty/Helpers/Util/Util.m
  src/Catty/Helpers/Util/Util.swift
  src/Catty/ViewController/BluetoothDeviceSelection/BluetoothDevicesTableViewController.swift
  src/Catty/ViewController/CatrobatTableViewController/SettingsTableViewController.swift
  src/Catty/ViewController/PrivacyPolicy/PrivacyPolicyViewController.swift
  src/Catty/ViewController/Stage/StagePresenterViewControllerResourcesExtension.swift
  src/Catty/ViewController/Upload/UploadViewController.swift
Labels: code review passed

#1604 CATTY-524 Convert Util methods to Swift 3/3
  src/Catty/Helpers/Util/Util.h
  src/Catty/Helpers/Util/Util.m
  src/Catty/Helpers/Util/Util.swift
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellMessageData.m
  src/CattyTests/Utils/UtilTests.swift
Labels: code review pending

#1617 CATTY-525 Convert SetLookBrick and SetBackgroundBrick to Swift
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/Bricks/Look/SetBackgroundBrick.h
  src/Catty/DataModel/Bricks/Look/SetBackgroundBrick.m
  src/Catty/DataModel/Bricks/Look/SetBackgroundBrick.swift
  src/Catty/DataModel/Bricks/Look/SetLookBrick.h
  src/Catty/DataModel/Bricks/Look/SetLookBrick.m
  src/Catty/DataModel/Bricks/Look/SetLookBrick.swift
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Look/SetBackgroundBrick+CBXMLHandler.h
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Look/SetBackgroundBrick+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Look/SetLookBrick+CBXMLHandler.h
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/Look/SetLookBrick+CBXMLHandler.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/LookBricks/SetBackgroundBrick+CBXMLHandler.swift
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Bricks/LookBricks/SetLookBrick+CBXMLHandler.swift
  src/Catty/Resources/Localization/en.lproj/Localizable.strings
  src/Catty/Supporting Files/Catty-Bridging-Header.h
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/SetBackgroundBrickCell.swift
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/SetLookBrickCell.h
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/SetLookBrickCell.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/Look/SetLookBrickCell.swift
  src/CattyTests/Bricks/SetBackgroundBrickTests.swift
  src/CattyTests/Bricks/SetLookBrickTests.swift
  src/CattyTests/Parser & Serialization/CatrobatLanguage0.93/Unit Tests/XMLParserBrickTests093.swift
Labels: in code review

#1537 CATTY-457 Copy actors or objects using the edit menu
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/Scene/Scene.swift
  src/Catty/Defines/LanguageTranslationDefines.h
  src/Catty/Defines/LanguageTranslationDefinesSwift.swift
  src/Catty/Resources/Localization/en.lproj/Localizable.strings
  src/Catty/ViewController/BaseViewController/BaseTableViewController.h
  src/Catty/ViewController/BaseViewController/BaseTableViewController.m
  src/Catty/ViewController/Continue&New/SceneTableViewController.m
  src/CattyTests/DataModel/SceneTest.swift
  src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift
  src/CattyUITests/MyFirstProjectTests.swift
  src/CattyUITests/SceneTVCTests.swift
Labels: code review passed

#1618 CATTY-497 Replace TTTAtributedLabel with ActiveLabel
  src/Cartfile
  src/Cartfile.resolved
  src/Catty.xcodeproj/project.pbxproj
  src/Catty.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  src/Catty/Resources/Licenses/ActiveLabel.license
  src/Catty/Resources/Licenses/TTTAttributedLabel.license
  src/Catty/Resources/Localization/en.lproj/Localizable.strings
  src/Catty/Settings.bundle/Acknowledgements.plist
  src/Catty/Settings.bundle/en.lproj/Acknowledgements.strings
  src/Catty/ViewController/Download/Details/ProjectDetailStoreViewController.h
  src/Catty/ViewController/Download/Details/ProjectDetailStoreViewController.m
  src/Catty/ViewController/Download/Details/ProjectDetailStoreViewControllerExtension.swift
  src/CattyTests/CattyTests-Bridging-Header.h
Labels: code review passed
