Repository Catrobat/Catty, pull requests merged in 2021-02, with the labels that each got.

#1580 CATTY-505 Uploading project with invalid token
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Store/StoreProjectUploader.swift
  src/CattyTests/Store/Upload/Fixture/StoreProjectUpload.uploadProject.fail.invalidToken.json
  src/CattyTests/Store/Upload/StoreProjectUploaderTests.swift
Labels: code review pending

#1577 CATTY-503 Appearance of Formula Editor
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Defines/LanguageTranslationDefines.h
  src/Catty/Defines/LanguageTranslationDefinesSwift.swift
  src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.h
  src/Catty/FormulaEditor/ViewController/FormulaEditorViewController.m
  src/Catty/Resources/Localization/en.lproj/Localizable.strings
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCells/BrickCell.h
  src/Catty/Views/Custom/ViewControllerTransitions/BaseTransition.h
  src/Catty/Views/Custom/ViewControllerTransitions/BaseTransition.m
  src/Catty/Views/Custom/ViewControllerTransitions/BrickTransition.h
  src/Catty/Views/Custom/ViewControllerTransitions/BrickTransition.m
  src/CattyUITests/Defines/LanguageTranslationDefinesUI.swift
  src/CattyUITests/FormulaEditorTests.swift
  src/CattyUITests/ScriptCollectionView/BrickCellTests.swift
  src/CattyUITests/ScriptCollectionView/ListTests.swift
  src/CattyUITests/ScriptCollectionView/ScriptCollectionVCTests.swift
  src/CattyUITests/ScriptCollectionView/VariableTests.swift
Labels: back in dev

#1582 CATTY-506 Merge EmbroideryStreams
  src/Catty/Embroidery/EmbroideryStream.swift
  src/CattyTests/Embroidery/EmbroideryDSTServiceTests.swift
  src/CattyTests/Embroidery/EmbroideryStreamTests.swift
Labels: in code review

#1589 CATTY-516 Remove deprecated TODO and FIXME
  src/Catty/BluetoothHelper/BluetoothHelper/Components/Peripheral.swift
  src/Catty/Helpers/Firmata/Firmata.swift
  src/Catty/PlayerEngine/CBCustomTypes.swift
Labels: code review pending

#1592 CATTY-512 Add missing tests for Formula mutableCopy
  src/CattyTests/Formula/FormulaTest.swift
Labels: code review pending

#1564 CATTY-372 FirebaseReporter Notification
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Extension&Delegate&Protocol/Extensions/NotificationExtension.swift
  src/Catty/Firebase/FirebaseAnalyticsReporter.swift
  src/Catty/Firebase/FirebaseCrashlyticsReporter.swift
  src/Catty/Supporting Files/Catty-Bridging-Header.h
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellFormulaData.m
  src/CattyTests/Firebase/FirebaseAnalyticsTests.swift
  src/CattyTests/Firebase/FirebaseCrashlyticsReporterTests.swift
  src/CattyTests/Views/BrickCells/Data/BrickCellFormulaDataTests.swift
Labels: back in dev

#1591 CATTY-513 Add missing tests for Formula display string
  src/CattyTests/Formula/FormulaTest.swift
Labels: in code review

#1583 CATTY-456 Convert Sound to Swift
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/DataModel/Bricks/Sound/PlaySoundAndWaitBrick.m
  src/Catty/DataModel/Bricks/Sound/PlaySoundBrick.m
  src/Catty/DataModel/Sound/Sound.h
  src/Catty/DataModel/Sound/Sound.m
  src/Catty/DataModel/Sound/Sound.swift
  src/Catty/DataModel/SpriteObject/SpriteObject.m
  src/Catty/Helpers/Util/Util.m
  src/Catty/IO/FileManager/CBFileManager.m
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Sound/Sound+CBXMLHandler.h
  src/Catty/Parser&Serialializer/New Parser & Serializer/XMLHandler/Sound/Sound+CBXMLHandler.m
  src/Catty/Parser&Serialializer/Old Parser/ProjectParser.m
  src/Catty/PlayerEngine/Instructions/Sound/PlaySoundAndWaitBrick+Instruction.swift
  src/Catty/PlayerEngine/Instructions/Sound/PlaySoundBrick+Instruction.swift
  src/Catty/Supporting Files/Catty-Bridging-Header.h
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainScript/ScriptCollectionViewController.m
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainSounds/SRViewController.m
  src/Catty/ViewController/Continue&New/MaintainObject/MaintainSounds/SoundsTableViewController.m
  src/Catty/Views/Custom/CollectionViewCells/BrickCellData/BrickCellSoundData.m
  src/CattyTests/Bricks/PlaySoundAndWaitBrickTests.swift
  src/CattyTests/Bricks/SetLookByIndexBrickTests.swift
  src/CattyTests/DataModel/SoundTest.swift
Labels: code review passed

#1571 CATTY-241 Add Swift extension for ProjectDetailStoreViewController
  src/Catty.xcodeproj/project.pbxproj
  src/Catty/Extension&Delegate&Protocol/Delegates/ProjectStoreDelegate.h
  src/Catty/Extension&Delegate&Protocol/Extensions/UIViewController/ProjectDetailStoreViewControllerReportExtension.swift
  src/Catty/ViewController/Download/Details/ProjectDetailStoreViewController.h
  src/Catty/ViewController/Download/Details/ProjectDetailStoreViewController.m
  src/Catty/ViewController/Download/Details/ProjectDetailStoreViewControllerExtension.swift
  src/Catty/Views/Custom/CreateView/CreateView.h
  src/Catty/Views/Custom/CreateView/CreateView.m
  src/CattyTests/CattyTests-Bridging-Header.h
Labels: code review pending
